import { toCents } from '@/lib/money';
import type { Coupon, Product } from '@/lib/types';

// Alguns preços e pesos foram escolhidos para testar os limites das regras:
// hub (2 un. = R$ 200,00, limite do frete grátis), headset (sem estoque)
// e halteres (pesado e barato, para cair no adicional de peso).
export const SEED_PRODUCTS: Product[] = [
  {
    id: 1,
    slug: 'teclado-mecanico-k1',
    name: 'Teclado Mecânico K1',
    description: 'Teclado mecânico compacto com switches lineares.',
    priceCents: toCents(349.9),
    stock: 15,
    weightGrams: 900,
  },
  {
    id: 2,
    slug: 'mouse-vertical-ergo',
    name: 'Mouse Vertical Ergonômico',
    description: 'Mouse vertical sem fio.',
    priceCents: toCents(189.9),
    stock: 20,
    weightGrams: 300,
  },
  {
    id: 3,
    slug: 'monitor-27-4k',
    name: 'Monitor 27" 4K',
    description: 'Monitor IPS 27 polegadas com resolução 4K.',
    priceCents: toCents(1999),
    stock: 5,
    weightGrams: 7000,
  },
  {
    id: 4,
    slug: 'cadeira-gamer-titan',
    name: 'Cadeira Gamer Titan',
    description: 'Cadeira com apoio lombar ajustável.',
    priceCents: toCents(1299),
    stock: 3,
    weightGrams: 22000,
  },
  {
    id: 5,
    slug: 'headset-studio-h5',
    name: 'Headset Studio H5',
    description: 'Headset fechado com microfone destacável.',
    priceCents: toCents(249.9),
    stock: 0,
    weightGrams: 400,
  },
  {
    id: 6,
    slug: 'webcam-hd-pro',
    name: 'Webcam HD Pro',
    description: 'Webcam 1080p com microfone duplo.',
    priceCents: toCents(159),
    stock: 40,
    weightGrams: 200,
  },
  {
    id: 7,
    slug: 'mousepad-xl',
    name: 'Mousepad XL',
    description: 'Mousepad 90x40cm com base antiderrapante.',
    priceCents: toCents(99.95),
    stock: 30,
    weightGrams: 800,
  },
  {
    id: 8,
    slug: 'hub-usbc-7em1',
    name: 'Hub USB-C 7 em 1',
    description: 'Hub com HDMI 4K e leitor de cartão.',
    priceCents: toCents(100),
    stock: 12,
    weightGrams: 150,
  },
  {
    id: 9,
    slug: 'kit-halteres-12kg',
    name: 'Kit de Halteres 12 kg',
    description: 'Par de halteres de 6 kg cada.',
    priceCents: toCents(89.9),
    stock: 10,
    weightGrams: 12000,
  },
];

export const SEED_COUPONS: Coupon[] = [
  {
    code: 'BEMVINDO10',
    type: 'PERCENT',
    value: 10,
    minSubtotalCents: toCents(50),
    maxDiscountCents: null,
    expiresAt: null,
    active: true,
  },
  {
    code: 'MEGA50',
    type: 'PERCENT',
    value: 50,
    minSubtotalCents: toCents(100),
    maxDiscountCents: toCents(80),
    expiresAt: null,
    active: true,
  },
  {
    code: 'FIXO25',
    type: 'FIXED',
    value: toCents(25),
    minSubtotalCents: toCents(25),
    maxDiscountCents: null,
    expiresAt: null,
    active: true,
  },
  {
    code: 'FIXO500',
    type: 'FIXED',
    value: toCents(500),
    minSubtotalCents: 0,
    maxDiscountCents: null,
    expiresAt: null,
    active: true,
  },
  {
    code: 'DESCONTO5',
    type: 'FIXED',
    value: toCents(5),
    minSubtotalCents: 0,
    maxDiscountCents: null,
    expiresAt: null,
    active: true,
  },
  {
    code: 'VERAO2024',
    type: 'PERCENT',
    value: 30,
    minSubtotalCents: 0,
    maxDiscountCents: null,
    expiresAt: '2024-12-31T23:59:59.000Z',
    active: true,
  },
  {
    code: 'DESATIVADO',
    type: 'PERCENT',
    value: 20,
    minSubtotalCents: 0,
    maxDiscountCents: null,
    expiresAt: null,
    active: false,
  },
];
